# Generated by Django 4.1.3 on 2023-04-10 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('event_name', models.CharField(max_length=40, null=True)),
                ('time_create', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.CharField(max_length=1000, null=True)),
                ('image_map_event', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField()),
                ('row', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=40, null=True)),
                ('seat', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('type', models.CharField(max_length=40, null=True)),
                ('age', models.CharField(max_length=40, null=True)),
                ('pdf_file', models.FileField(null=True, upload_to='pdfs/')),
                ('category', models.CharField(max_length=40, null=True)),
                ('time_create', models.DateTimeField(auto_now=True, null=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.event')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, null=True)),
                ('reason', models.CharField(max_length=40, null=True)),
                ('price', models.FloatField(null=True)),
                ('time_create', models.DateTimeField(auto_now=True, null=True)),
                ('id_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buyer', to=settings.AUTH_USER_MODEL)),
                ('id_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller', to=settings.AUTH_USER_MODEL)),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ticket')),
            ],
        ),
    ]
