# Generated by Django 4.1.7 on 2023-05-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_account_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='id',
            new_name='id_deal',
        ),
    ]
