# Generated by Django 4.1.7 on 2023-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_rename_id_deal_id_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='status_location',
            field=models.CharField(default='The event has not yet occurred', max_length=40, null=True),
        ),
    ]
